name: check-and-format-code-on-pr

on:
  pull_request:
    branches: [dev, main, prod]
    types: [open, reopened, synchronize]


jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write  # Add this line

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.4"

      - name: Copy pre-commit config
        run: |
          mkdir -p .github/workflows
          curl -O https://raw.githubusercontent.com/oslokommune-reg/.github/prod/.github/workflows/config/.pre-commit-config.yaml

      - name: Run pre-commit on changed files
        run: |
          pre-commit run --from-ref origin/${{ github.event.pull_request.base.sha }} --to-ref ${{ github.sha }}
          git diff --exit-code || echo "Files were modified by pre-commit. Changes will be committed."
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Applied formatting"
