name: check-and-format-code-on-pr

on:
  push:
    branches:
     - main
     - dev
     - prod
  pull_request:
    branches:
      - dev
      - prod

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.4"

      - name: Copy pre-commit config
        run: |
          mkdir -p .github/workflows
          curl -O https://raw.githubusercontent.com/oslokommune-reg/.github/prod/.github/workflows/config/.pre-commit-config.yaml

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
          git diff --exit-code || echo "Files were modified by pre-commit. Changes will be committed."
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Applied formatting"
