name: format-and-verify-code

on:
  pull_request:
    branches: [dev, main, prod]
    types: [opened, synchronize, reopened]

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install pre-commit
        run: pip install pre-commit
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.4"
          
      - name: Copy pre-commit config
        run: |
          mkdir -p .github/workflows
          curl -O https://raw.githubusercontent.com/oslokommune-reg/.github/prod/.github/workflows/config/.pre-commit-config.yaml
     
      - name: Run pre-commit on changed files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin ${{ github.base_ref }}
            pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD
          else
            pre-commit run --all-files
          fi
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Applied formatting"

  verify-formatting:
    needs: format-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Check for unstaged changes
        run: |
          if ! git diff --exit-code; then
            echo "Formatting check failed. Please close and reopen the pull request to trigger new."
            exit 1
          fi
