name: format-code

on:
  push:
    branches:
      - '**'
      - '!dev'
      - '!main'
      - '!prod'
  pull_request_target:
    branches: [dev, main, prod]
    types: [opened, synchronize, reopened]

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CODE_FORMATTER_PAT }} 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.4"

      - name: Copy pre-commit config
        run: |
          mkdir -p .github/workflows
          curl -O https://raw.githubusercontent.com/oslokommune-reg/.github/prod/.github/workflows/config/.pre-commit-config.yaml

      - name: Run pre-commit on changed files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin ${{ github.base_ref }}
            pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD
          else
            pre-commit run --all-files
          fi
        continue-on-error: true

      - name: Check for changes
        id: git-check
        run: |
          git status
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Debug info
        run: |
          echo "Changes detected: ${{ steps.git-check.outputs.changes }}"
          git status
          git diff

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Applied formatting [skip ci]"
          branch: ${{ github.head_ref }}

      - name: Check if commit was made
        run: |
          git log -1
          git status
