name: Format

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Create pre-commit config
        run: |
          cat > .pre-commit-config.yaml <<EOL
          repos:
            - repo: https://github.com/tconbeer/sqlfmt
              rev: v0.18.0
              hooks:
                - id: sqlfmt
                  language_version: python
                  additional_dependencies: [".[jinjafmt]"]
          EOL

      - name: Run pre-commit
        run: pre-commit run --all-files

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply sqlfmt formatting"
          file_pattern: '*.sql'